### PR TITLE
set Content-Length

### PR DESCRIPTION
**Pull request by tnclong**

### CODE REVIEW

**Comment by tnclong** [comment]
> //  Additionally, if the total size of all written
> 	// data is under a few KB and there are no Flush calls, the?>
>	// Content-Length header is added automatically.

**Comment by tnclong** [comment]
The write method give us `err`, Please have a process?

**Comment by sunfmin** [comment]
Add a test to verify that a Content-Length is not added with larger body.

**Comment by tnclong** [comment]
@bodhi  https://github.com/theplant/lacoste3/issues/2333

**Comment by bodhi** [comment]
I see, and the K8s ingress (or something upstream) will automatically compress the response if it has `Content-Length` set?

**Comment by tnclong** [comment]
share you in original issue.

**Comment by tnclong** [comment]
@sunfmin add in https://github.com/theplant/prottp/pull/14/commits/f8db47e24dc2962d1863f47563cd2c6f794d8c29

**Comment by tnclong** [comment]
Do extra things in the pull reuqest since we face more problem.

1. add whitespace in content-type after ;

That maybe be let Content-Type work well with gzip_types in nginx-ingress.

Just a try.

**Comment by tnclong** [comment]
Roll 2:

remove Content-Type content after `;`. able to work in `nginx-ingress`.

https://github.com/theplant/prottp/pull/14/commits/f571140d768efa143782d6c5dd19f3f6ae7e086e

**Comment by tnclong** [comment]
@sunfmin I think the work is done. When you have time, please hava a review.

**Pull request merged**
